version: '3.7'
services:
  frontend:
    image: node:20-alpine3.19
    working_dir: /app
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    image: python:3.12
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app

  db:
    image: postgres:16.4-alpine3.19
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "link_keeper_user"
      POSTGRES_PASSWORD: "pgdev"
      POSTGRES_DB: "link_keeper"
    ports:
      - "5432:5432"

volumes:
  db_volume:
